"""Generate a PyMOL script illustrating the O-ring effect: dry core vs wet rim.

WHAT THIS FIGURE ARGUES
    Buried surface area and buried-ness are not the same quantity, and hot-spot prediction
    lives in the gap between them. The default figure case is 3M62 (Ufd2 / Rad23 UBL), where
    the two are maximally decoupled:

        Tyr97 (chain A)   buries  29.8 A^2   and retains  1.07 A^2 exposed  -> 99.6% dry
        Phe9  (chain B)   buries  80.1 A^2   and retains 69.73 A^2 exposed  -> 29% still wet

    Phe9 buries 2.7x MORE absolute area than Tyr97 and is still soaking in solvent when
    bound, because it sits on a broad shallow rim. Tyr97 buries less than half as much, but
    what it does bury is essentially all of it, inside a small occluded pocket.

    The consequence, measured: Tyr97 has ddG 4.48 kcal/mol and is the strongest residue in
    the interface; Phe9 has ddG 1.00 and is not a hot spot. Ranking by buried area puts Phe9
    FIRST and Tyr97 FOURTEENTH of seventeen. Our model puts Tyr97 first and Phe9 fourth.

    Bogan & Thorn's O-ring model predicts exactly this: a hot spot needs water excluded for
    its interactions to pay off energetically, and a ring of peripheral residues provides
    that occlusion while contributing little itself. Buried surface area measures how much
    of an interface a residue covers. Relative accessibility in the bound state measures
    whether it is dry. Only the second one predicts energy.

Usage::

    .\\.venv\\Scripts\\python.exe scripts\\make_pymol_oring.py
    pymol figures\\oring_3m62.pml
"""

from __future__ import annotations

import argparse
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

TEMPLATE = '''# =====================================================================
#  O-RING FIGURE  --  {pdb}: {core_label} (dry core) vs {rim_label} (wet rim)
#  generated by scripts/make_pymol_oring.py
# =====================================================================
#
#  HOW TO RUN
#    pymol {outname}
#  or, from an open PyMOL session:
#    @{outname}
#
#  Needs an internet connection the first time (it fetches {pdb} from the PDB).
#  To work offline, drop a local {pdblower}.pdb next to this script and replace the
#  `fetch` line below with:  load {pdblower}.pdb, {pdb}
#
#  WHAT YOU ARE LOOKING AT
#    {core_label:<28} GREEN   ddG {core_ddg:.2f}   model rank #{core_mrank}, buried-area rank #{core_nrank}
#    {rim_label:<28} RED     ddG {rim_ddg:.2f}   model rank #{rim_mrank}, buried-area rank #{rim_nrank}
#
#    The red residue buries MORE surface area than the green one and matters LESS.
#    That inversion is the whole point of the figure.
#
#  SCENES (press the F-keys, or click the scene names in the bottom bar)
#    F1  overview     both chains, cartoon, the two residues as sticks
#    F2  pocket       partner chain hidden, surface on the host -- {core_label} sits in a hole
#    F3  rim          same view, showing {rim_label} out on the open face
#    F4  occlusion    both surfaces, semi-transparent, to compare depth directly
#    F5  slab         clipped cross-section through the interface
#
# =====================================================================

reinitialize
fetch {pdb}, async=0

# ---- clean up: keep only the two chains of interest, drop waters and ligands --------
remove not (chain {chain_a} or chain {chain_b})
remove solvent
remove hydrogens
remove not polymer

# ---- named selections ----------------------------------------------------------------
select host,      chain {chain_a}
select partner,   chain {chain_b}
select core_res,  chain {core_chain} and resi {core_resi}
select rim_res,   chain {rim_chain} and resi {rim_resi}

# the interface itself: residues within 5 A of the other chain (our pipeline's cutoff)
select iface_a,   byres (chain {chain_a} within 5 of chain {chain_b})
select iface_b,   byres (chain {chain_b} within 5 of chain {chain_a})
select interface, iface_a or iface_b

# ---- base style -----------------------------------------------------------------------
hide everything
bg_color white
set ray_opaque_background, 0
show cartoon
set cartoon_transparency, 0.55
color grey80, host
color palecyan, partner

# interface residues get a faint tint so the patch is legible
color grey60, iface_a
color lightteal, iface_b

# ---- the two protagonists --------------------------------------------------------------
show sticks, (core_res or rim_res) and not name N+C+O
color {core_color}, core_res
color {rim_color}, rim_res
set stick_radius, 0.25
util.cnc("core_res or rim_res")          # keep heteroatom colouring on O/N
color {core_color}, core_res and elem C
color {rim_color}, rim_res and elem C

show spheres, (core_res or rim_res) and name CA
set sphere_scale, 0.30

label core_res and name CA, "{core_label}  ddG {core_ddg:.1f}"
label rim_res  and name CA, "{rim_label}  ddG {rim_ddg:.1f}"
set label_size, 16
set label_color, black
set label_outline_color, white
set label_position, (0, 1.6, 0)

# ---- surface quality --------------------------------------------------------------------
set surface_quality, 1
set transparency, 0.45
set two_sided_lighting, on
set ray_shadows, off
set antialias, 2
set ambient, 0.25
set specular, 0.15

# =====================================================================
#  MEASURE IT -- do not take the figure's word for it
#  dot_solvent 1 gives solvent-ACCESSIBLE area (what our pipeline computes).
#  The numbers printed here should reproduce the pipeline's SASA columns.
# =====================================================================
set dot_solvent, 1
set dot_density, 3

print ""
print "=============================================================="
print " SOLVENT-ACCESSIBLE AREA  (A^2)   -- measured live by PyMOL"
print "=============================================================="

create _host_only,    host
create _partner_only, partner

python
from pymol import cmd
core = "chain {core_chain} and resi {core_resi}"
rim  = "chain {rim_chain} and resi {rim_resi}"
# host/partner copies let us measure the UNBOUND state of each residue
core_unbound = cmd.get_area("_{core_copy} and resi {core_resi}")
rim_unbound  = cmd.get_area("_{rim_copy} and resi {rim_resi}")
core_bound   = cmd.get_area(core)
rim_bound    = cmd.get_area(rim)
def row(tag, unbound, bound):
    buried = unbound - bound
    pct = 100.0 * buried / unbound if unbound else 0.0
    print(" %-14s unbound %7.1f   bound %7.1f   buried %7.1f  (%.1f%% occluded)"
          % (tag, unbound, bound, buried, pct))
row("{core_label} (core)", core_unbound, core_bound)
row("{rim_label} (rim)",  rim_unbound,  rim_bound)
print("")
print(" The rim residue buries MORE area yet stays exposed; the core residue")
print(" buries less and ends up almost completely dry. Area != burial.")
python end

delete _host_only
delete _partner_only

# =====================================================================
#  SCENES
# =====================================================================

# ---- F1: overview -----------------------------------------------------------------------
# Orient on the interface so the contact patch faces the viewer, then back off slightly.
hide surface
orient interface
zoom interface, 4
turn x, -15
scene overview, store, message="Overview: {core_label} (green, dry core) vs {rim_label} (red, wet rim)"

# ---- F2: the pocket ---------------------------------------------------------------------
# Hide the partner chain and put a surface on the host. The core residue should now be
# visible at the bottom of a depression -- you are looking into the hole it occupies.
# BEST ANGLE: orient on the core residue, then roll with `turn y, 10` a few times until
# the pocket mouth faces you. The green should look recessed, not raised.
hide everything
show surface, host
color grey90, host
color {core_color}, core_res
show sticks, core_res and not name N+C+O
color {core_color}, core_res and elem C
orient core_res
zoom core_res, 8
turn x, -10
scene pocket, store, message="{core_label} sits in an occluded pocket -- only {core_bound:.1f} A^2 left exposed when bound"

# ---- F3: the rim ------------------------------------------------------------------------
# Same surface, same chain family, but now look at the rim residue. It should read as
# sitting ON the surface rather than inside it -- a bump, not a hole.
hide everything
show surface, partner
color palecyan, partner
color {rim_color}, rim_res
show sticks, rim_res and not name N+C+O
color {rim_color}, rim_res and elem C
orient rim_res
zoom rim_res, 8
scene rim, store, message="{rim_label} sits on an open shallow face -- {rim_bound:.1f} A^2 still solvent-exposed"

# ---- F4: occlusion comparison -------------------------------------------------------------
# Both surfaces, semi-transparent, so you can see one residue swallowed and one perched.
# BEST ANGLE: orient on `interface`, then `turn y, 90` to view the contact edge-on. The
# depth difference is clearest in profile, not face-on.
hide everything
show surface, host or partner
set transparency, 0.55
color grey90, host
color palecyan, partner
color {core_color}, core_res
color {rim_color}, rim_res
show sticks, (core_res or rim_res) and not name N+C+O
color {core_color}, core_res and elem C
color {rim_color}, rim_res and elem C
orient interface
turn y, 90
zoom interface, 3
scene occlusion, store, message="Edge-on: green is swallowed by the interface, red perches on its rim"

# ---- F5: slab / cross-section ---------------------------------------------------------------
# Clipping planes cut through the complex so you see the interior. This is the single most
# convincing view: the green residue appears inside the sealed region, the red one outside.
# If the slab cuts in the wrong place, adjust with `clip slab, 12` or scroll-wheel drag.
hide everything
show surface, host or partner
set transparency, 0.25
color grey90, host
color palecyan, partner
color {core_color}, core_res
color {rim_color}, rim_res
orient interface
turn y, 90
clip slab, 16
scene slab, store, message="Cross-section: the O-ring. Green inside the sealed core, red on the open rim"

# ---- land on the overview ------------------------------------------------------------------
scene overview, recall

print ""
print " Scenes stored: overview (F1), pocket (F2), rim (F3), occlusion (F4), slab (F5)"
print " Ray-trace a figure with:  ray 1600, 1200   then   png oring_figure.png, dpi=300"
print ""

# ---- camera / rendering notes ----------------------------------------------------------------
#  WHICH ANGLE ACTUALLY SHOWS DEPTH
#    Face-on views flatten the difference -- both residues look like coloured patches.
#    Depth reads in PROFILE. Use scene `occlusion` or `slab` and rotate with `turn y, 90`
#    from the orient-on-interface position so you are looking ALONG the interface plane.
#
#  IF THE POCKET IS NOT OBVIOUS IN F2
#    Try:  set surface_cavity_mode, 1     (emphasises concavity)
#          set transparency, 0.0          (opaque surface reads depth better than glass)
#    A cavity is easier to see opaque; overlapping transparent surfaces muddy it.
#
#  FOR A PUBLICATION FIGURE
#    set ray_trace_mode, 1        # outlines, good for print
#    set ray_trace_gain, 0.008
#    bg_color white
#    ray 2400, 1800
#    png {pdblower}_oring.png, dpi=600
'''


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--pdb", default="3M62")
    ap.add_argument("--chains", default="A,B", help="host,partner")
    ap.add_argument("--core", default="A:97:TYR",
                    help="the dry-core residue, CHAIN:RESI:RESNAME")
    ap.add_argument("--rim", default="B:9:PHE",
                    help="the wet-rim residue, CHAIN:RESI:RESNAME")
    ap.add_argument("--core-stats", nargs=4, type=float, default=[4.475, 1, 14, 1.07],
                    metavar=("DDG", "MODEL_RANK", "NAIVE_RANK", "SASA_BOUND"))
    ap.add_argument("--rim-stats", nargs=4, type=float, default=[0.996, 4, 1, 69.73],
                    metavar=("DDG", "MODEL_RANK", "NAIVE_RANK", "SASA_BOUND"))
    ap.add_argument("--out", type=Path, default=None)
    args = ap.parse_args()

    ca, cb = (x.strip() for x in args.chains.split(","))
    core_chain, core_resi, core_name = args.core.split(":")
    rim_chain, rim_resi, rim_name = args.rim.split(":")
    out = args.out or (REPO_ROOT / "figures" / f"oring_{args.pdb.lower()}.pml")

    text = TEMPLATE.format(
        pdb=args.pdb.upper(), pdblower=args.pdb.lower(),
        outname=out.name,
        chain_a=ca, chain_b=cb,
        core_chain=core_chain, core_resi=core_resi,
        rim_chain=rim_chain, rim_resi=rim_resi,
        core_label=f"{core_name}{core_resi}", rim_label=f"{rim_name}{rim_resi}",
        core_color="forest", rim_color="firebrick",
        core_ddg=args.core_stats[0], core_mrank=int(args.core_stats[1]),
        core_nrank=int(args.core_stats[2]), core_bound=args.core_stats[3],
        rim_ddg=args.rim_stats[0], rim_mrank=int(args.rim_stats[1]),
        rim_nrank=int(args.rim_stats[2]), rim_bound=args.rim_stats[3],
        core_copy="host_only" if core_chain == ca else "partner_only",
        rim_copy="host_only" if rim_chain == ca else "partner_only",
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")

    print(f"  wrote {out}  ({out.stat().st_size/1024:.1f} KB)")
    print(f"  core : {core_name}{core_resi} chain {core_chain}  "
          f"ddG {args.core_stats[0]:.2f}, model #{int(args.core_stats[1])}, "
          f"buried-area #{int(args.core_stats[2])}")
    print(f"  rim  : {rim_name}{rim_resi} chain {rim_chain}  "
          f"ddG {args.rim_stats[0]:.2f}, model #{int(args.rim_stats[1])}, "
          f"buried-area #{int(args.rim_stats[2])}")
    print(f"\n  run with:  pymol {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
